lang: en
project:
  type: website
  output-dir: docs
  resources: [CNAME, .nojekyll]

execute:
  freeze: auto

website:
  title: "Setonix"
  image: www/images/logos/setonix-black.png
  site-url: https://setonix.art
  google-analytics: 
    tracking-id: "G-L42NDQR8R1"
    anonymize-ip: true
    storage: none
  navbar:
    logo: www/images/logos/setonix-white.png
    logo-alt: "Setonix"
    right:
      - posts/index.qmd
      - faq.qmd
      - icon: fire
        href: https://fetlife.com/users/16247449
      - icon: instagram
        href: https://instagram.com/setonix.shibari
      - text: "![](/www/images/logos/tumblr.svg){height='1em'}"
        href: https://www.tumblr.com/setonix-shibari
      - text: "![](/www/images/logos/bsky.svg){height='1em'}"
        href: https://bsky.app/profile/setonix-shibari.bsky.social
format:
  html:
    theme: [darkly, www/styles.scss]
    fontsize: 1.1em



