lang: en
project:
  type: website
  output-dir: docs
  resources: [CNAME, .nojekyll, .well-known/atproto-did]

execute:
  freeze: auto

website:
  title: "Setonix"
  image: www/images/logos/setonix-black.png
  site-url: https://setonix.art
  google-analytics: 
    tracking-id: "G-L42NDQR8R1"
    anonymize-ip: true
    storage: none
  navbar:
    logo: www/images/logos/setonix-white.png
    logo-alt: "Setonix"
    right:
      - posts/index.qmd
      - photos/index.qmd
      - sets/index.qmd
      - faq.qmd
      - text: "![](/www/images/logos/patreon.svg){height='1em'}"
        aria-label: Patreon
        href: https://patreon.com/Setonix
      - text: "![](/www/images/logos/fetlife.svg){height='1.3em'}"
        aria-label: FetLife
        href: https://fetlife.com/users/16247449
      - text: "![](/www/images/logos/tumblr.svg){height='1em'}"
        aria-label: Tumblr
        href: https://www.tumblr.com/setonix-shibari
      - text: "![](/www/images/logos/bsky.svg){height='1em'}"
        aria-label: BlueSky
        href: https://bsky.app/profile/setonix.art
      - icon: envelope-heart-fill
        aria-label: Contact Me
        href: mailto:setonix.shibari@gmail.com
  page-footer:
    right: 
      - text: "![](/www/images/logos/cc-by-nc-sa.svg){height='1.5em'}"
        href: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en

format:
  html:
    theme: [darkly, www/styles.scss]
    fontsize: 1.1em
#    include-after-body: www/setonix.js



